### ISSUE TITLE
Error in get(name, envir = envir) : object 'usingMDCCfinder' not found

### ISSUE THREAD

**Issue by brenaac** [iramosgutierrez/randtip#11]
Hi all

I find the error "Error in get(name, envir = envir) : object 'usingMDCCfinder' not found" when trying to use "info2input" function. 

I tried different info dataframe (with and without supra generic information my.info object build using list and backbone mode...) and I got the same error in every case.

I'm keen to answer any question about my data.

Many thanks

**Comment by brenaac** [comment]
I also couldn't use the "check_info" function

my.check <- check_info(my.info.noranks, edited_tree)

ncores argument was not provided. Using all but one of system cores.

Searching for possible misspellings
Error in get(name, envir = envir) : object 'check_phyletic' not found

**Comment by iramosgutierrez** [comment]
Hi there,
I have not seen this error before, but as I have seen from other issues it might be an error of R or RStudio, rather than the package, thus it might get solved by reopening/reinstalling those, or trying to reinstall the package.
 (see https://github.com/im3sanger/dndscv/issues/47 or https://github.com/benjjneb/dada2/issues/766)

Hope this has been helpful, but let me know if it wasn't!
Ignacio.

**Comment by iramosgutierrez** [comment]
As far as I'm seeing, this might be an error due to the parallelization process. In case you are using just one core, you can use the argument parallelize=F, and it should work. 

However, thanks for the warning about the missfunctioning!
Ignacio.

**Comment by h-lima** [comment]
Hello brennac, please let us know your system details so we can try to replicate the issue. The output of `sessionInfo()` would be great.

**Comment by brenaac** [comment]
Hi all

Thanks for the quick reply. I used parallelize=F and it worked. 

Many thanks!
