### ISSUE TITLE
Error: std::bad_alloc

### ISSUE THREAD

**Issue by cassiabitencourt** [iramosgutierrez/randtip#12]
Hi folks: 

I encountered an error that appears specific to the package, and I guess here is the best place to help me resolve it. The error message is as follows: **Error: std::bad_alloc** The error persists even when I am not using the loop or running in an HPC cluster. I would like to know what you think about managing this issue. I would appreciate any help. Thank you so much!

**Comment by iramosgutierrez** [comment]
Hi Cassia!
I have never seen this error, but from what I understand in other discussions, this may be due to lack of memory in your system; maybe you should request more when using the cluster (does this error persist when working in your local machine?).
However, maybe @h-lima can shed some light on this issue!
Ignacio.

**Comment by h-lima** [comment]
Hello Cassia, 

Never encountered that error while running the package. That is usually a C++ error encountered when you run out of memory. Randtip does not use C++ code directly, but it indeed depends on packages that have C++ code, so it must be during a call to a function of another package.
Check if your memory is enough, and if not allocate more memory for your jobs in the cluster. If you can discard the "out of memory" issue, could you provide us with a minimal reproducible example and your system details so we can try to reproduce and track any issue in the code?
